/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CapitalRouteImport } from './routes/capital'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as AccessRouteImport } from './routes/access'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesTranslationRouteImport } from './routes/services.translation'
import { Route as ServicesStudentSupportRouteImport } from './routes/services.student-support'
import { Route as ServicesRestaurantRouteImport } from './routes/services.restaurant'
import { Route as ServicesForeignSupportRouteImport } from './routes/services.foreign-support'
import { Route as ServicesFoodRouteImport } from './routes/services.food'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CapitalRoute = CapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesTranslationRoute = ServicesTranslationRouteImport.update({
  id: '/translation',
  path: '/translation',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesStudentSupportRoute = ServicesStudentSupportRouteImport.update({
  id: '/student-support',
  path: '/student-support',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRestaurantRoute = ServicesRestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesForeignSupportRoute = ServicesForeignSupportRouteImport.update({
  id: '/foreign-support',
  path: '/foreign-support',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFoodRoute = ServicesFoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/business': typeof BusinessRoute
  '/capital': typeof CapitalRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/food': typeof ServicesFoodRoute
  '/services/foreign-support': typeof ServicesForeignSupportRoute
  '/services/restaurant': typeof ServicesRestaurantRoute
  '/services/student-support': typeof ServicesStudentSupportRoute
  '/services/translation': typeof ServicesTranslationRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/business': typeof BusinessRoute
  '/capital': typeof CapitalRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/services/food': typeof ServicesFoodRoute
  '/services/foreign-support': typeof ServicesForeignSupportRoute
  '/services/restaurant': typeof ServicesRestaurantRoute
  '/services/student-support': typeof ServicesStudentSupportRoute
  '/services/translation': typeof ServicesTranslationRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access': typeof AccessRoute
  '/business': typeof BusinessRoute
  '/capital': typeof CapitalRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/food': typeof ServicesFoodRoute
  '/services/foreign-support': typeof ServicesForeignSupportRoute
  '/services/restaurant': typeof ServicesRestaurantRoute
  '/services/student-support': typeof ServicesStudentSupportRoute
  '/services/translation': typeof ServicesTranslationRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access'
    | '/business'
    | '/capital'
    | '/company'
    | '/contact'
    | '/services'
    | '/services/food'
    | '/services/foreign-support'
    | '/services/restaurant'
    | '/services/student-support'
    | '/services/translation'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access'
    | '/business'
    | '/capital'
    | '/company'
    | '/contact'
    | '/services/food'
    | '/services/foreign-support'
    | '/services/restaurant'
    | '/services/student-support'
    | '/services/translation'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/access'
    | '/business'
    | '/capital'
    | '/company'
    | '/contact'
    | '/services'
    | '/services/food'
    | '/services/foreign-support'
    | '/services/restaurant'
    | '/services/student-support'
    | '/services/translation'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessRoute: typeof AccessRoute
  BusinessRoute: typeof BusinessRoute
  CapitalRoute: typeof CapitalRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capital': {
      id: '/capital'
      path: '/capital'
      fullPath: '/capital'
      preLoaderRoute: typeof CapitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/translation': {
      id: '/services/translation'
      path: '/translation'
      fullPath: '/services/translation'
      preLoaderRoute: typeof ServicesTranslationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/student-support': {
      id: '/services/student-support'
      path: '/student-support'
      fullPath: '/services/student-support'
      preLoaderRoute: typeof ServicesStudentSupportRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/restaurant': {
      id: '/services/restaurant'
      path: '/restaurant'
      fullPath: '/services/restaurant'
      preLoaderRoute: typeof ServicesRestaurantRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/foreign-support': {
      id: '/services/foreign-support'
      path: '/foreign-support'
      fullPath: '/services/foreign-support'
      preLoaderRoute: typeof ServicesForeignSupportRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/food': {
      id: '/services/food'
      path: '/food'
      fullPath: '/services/food'
      preLoaderRoute: typeof ServicesFoodRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesFoodRoute: typeof ServicesFoodRoute
  ServicesForeignSupportRoute: typeof ServicesForeignSupportRoute
  ServicesRestaurantRoute: typeof ServicesRestaurantRoute
  ServicesStudentSupportRoute: typeof ServicesStudentSupportRoute
  ServicesTranslationRoute: typeof ServicesTranslationRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesFoodRoute: ServicesFoodRoute,
  ServicesForeignSupportRoute: ServicesForeignSupportRoute,
  ServicesRestaurantRoute: ServicesRestaurantRoute,
  ServicesStudentSupportRoute: ServicesStudentSupportRoute,
  ServicesTranslationRoute: ServicesTranslationRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessRoute: AccessRoute,
  BusinessRoute: BusinessRoute,
  CapitalRoute: CapitalRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
